require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '11.0'

target 'GumTestApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'GumTestAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'GumTestApp-tvOS' do
  # Pods for GumTestApp-tvOS

  target 'GumTestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
