name: iOS CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  ios-compile:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Cache cocoapods
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ./examples/GumTestApp/ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install node modules
      run: npm install

    - name: Install example node modules
      working-directory: ./examples/GumTestApp/
      run: npm install

    - name: Pod install
      working-directory: ./examples/GumTestApp/ios
      run: pod install

    - name: Compile iOS Example
      working-directory: ./examples/GumTestApp/ios
      run: |
        set -o pipefail && \
        xcodebuild -workspace GumTestApp.xcworkspace/ \
          -scheme GumTestApp \
          -destination generic/platform=iOS \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_ENTITLEMENTS="" \
          CODE_SIGNING_ALLOWED="NO" clean build \
        | xcpretty
